

#ifndef MARKET_SERVER_BOUND_HEADER_INCLUDED
#define MARKET_SERVER_BOUND_HEADER_INCLUDED

enum MS_Client_Type
{
    MS_CLIENT_PLAYER = 1,
    MS_CLIENT_US = 2
};


#endif // MARKET_SERVER_BOUND_HEADER_INCLUDED
