

#ifndef USER_SERVER_BOUND_HEADER_INCLUDED
#define USER_SERVER_BOUND_HEADER_INCLUDED

enum US_Client_Type
{
    US_CLIENT_PLAYER = 1,
    US_CLIENT_RS = 2,
    US_CLIENT_MS = 3
};


#endif // USER_SERVER_BOUND_HEADER_INCLUDED
